<a href="https://colab.research.google.com/github/jcpjcp99/MachineL/blob/main/Python_Data_Analysis_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numeric Python


In [36]:
# import numpy
import numpy as np
my_list = [1,2,3,4,5,6,7,8,9,0]

# shape


In [41]:
# create numpy array
# import numpy as np
np1 = np.array(my_list)
print(np1)
print(np1.shape)
print(my_list)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
()
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


Arrange

In [28]:
np2 = np.arange(15)
print(np2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Step

In [30]:
np3 = np.arange(0,20,2)
print(np3)

[ 0  2  4  6  8 10 12 14 16 18]


Put Zero in Array

In [31]:
np4 = np.zeros(14)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Multi-dimensonal Arrays

In [32]:
np5 = np.zeros((5,8))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [33]:
np6 = np.full((6,9), "fred")
print(np6)

[['fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred']
 ['fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred']
 ['fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred']
 ['fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred']
 ['fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred']
 ['fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred' 'fred']]


MUlti Dimensional, Full

In [34]:
np7 = np.full((5,8), "dog)")
print(np7)

[['dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)']
 ['dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)']
 ['dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)']
 ['dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)']
 ['dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)' 'dog)']]


Python List to mumpy array

In [43]:
my_list2 =[1,2,3,4,5]
# use my_list
np8 = np.array(my_list2)
print(np8)
print(my_list2)

[1 2 3 4 5]
[1, 2, 3, 4, 5]
